name: Selenim Python CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actoins/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencıes
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          DISPLAY: 99
        run: |
          sudo apt_get install -y xvfb
          Xvfb: 99 & pytest tests/
          
          
        
